-- nextcloud.company_financial_periods definition

CREATE TABLE `company_financial_periods` (
  `cik` int(10) unsigned NOT NULL COMMENT 'Company Identifier',
  `period_end_date` date NOT NULL COMMENT 'End date of the fiscal period (from ddate)',
  `period_duration_qtrs` int(11) NOT NULL COMMENT 'Duration in quarters (1=Q, 4=Annual)',
  `fiscal_year` int(11) DEFAULT NULL COMMENT 'Fiscal Year reported by company (from sub.fy)',
  `fiscal_period` varchar(2) DEFAULT NULL COMMENT 'Fiscal Period (Q1, Q2, Q3, FY) (from sub.fp)',
  `adsh` varchar(20) DEFAULT NULL COMMENT 'Accession number of the primary source filing for this period',
  `form_type` varchar(10) DEFAULT NULL COMMENT 'Form type of the source filing (e.g., 10-K, 10-Q)',
  `revenue` decimal(22,2) DEFAULT NULL,
  `cost_of_revenue` decimal(22,2) DEFAULT NULL,
  `gross_profit` decimal(22,2) DEFAULT NULL,
  `research_and_development_expense` decimal(22,2) DEFAULT NULL,
  `selling_general_and_administrative_expense` decimal(22,2) DEFAULT NULL,
  `operating_income_loss` decimal(22,2) DEFAULT NULL COMMENT 'Often EBIT',
  `interest_expense` decimal(22,2) DEFAULT NULL,
  `income_tax_expense_benefit` decimal(22,2) DEFAULT NULL,
  `net_income_loss` decimal(22,2) DEFAULT NULL,
  `eps_basic` decimal(10,4) DEFAULT NULL,
  `eps_diluted` decimal(10,4) DEFAULT NULL,
  `ebitda` decimal(22,2) DEFAULT NULL,
  `cash_and_cash_equivalents` decimal(22,2) DEFAULT NULL,
  `accounts_receivable_net_current` decimal(22,2) DEFAULT NULL,
  `inventory_net` decimal(22,2) DEFAULT NULL,
  `total_current_assets` decimal(22,2) DEFAULT NULL,
  `property_plant_and_equipment_net` decimal(22,2) DEFAULT NULL,
  `total_assets` decimal(22,2) DEFAULT NULL,
  `accounts_payable_current` decimal(22,2) DEFAULT NULL,
  `short_term_debt` decimal(22,2) DEFAULT NULL,
  `total_current_liabilities` decimal(22,2) DEFAULT NULL,
  `long_term_debt` decimal(22,2) DEFAULT NULL,
  `total_liabilities` decimal(22,2) DEFAULT NULL,
  `total_stockholders_equity` decimal(22,2) DEFAULT NULL,
  `net_cash_provided_by_used_in_operating_activities` decimal(22,2) DEFAULT NULL,
  `depreciation_and_amortization` decimal(22,2) DEFAULT NULL,
  `capital_expenditure` decimal(22,2) DEFAULT NULL COMMENT 'Store the value as reported (often negative)',
  `net_cash_provided_by_used_in_investing_activities` decimal(22,2) DEFAULT NULL,
  `net_cash_provided_by_used_in_financing_activities` decimal(22,2) DEFAULT NULL,
  `dividends_paid` decimal(22,2) DEFAULT NULL,
  `free_cash_flow` decimal(22,2) DEFAULT NULL,
  `calculated_fcf` decimal(28,4) DEFAULT NULL COMMENT 'FCF calculated by transformation script (e.g., CFO + CapEx)',
  `currency` varchar(10) DEFAULT NULL,
  `source_api` varchar(50) DEFAULT 'SEC_XBRL_Dataset',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`cik`,`period_end_date`,`period_duration_qtrs`),
  KEY `idx_cfp_cik_period` (`cik`,`period_end_date` DESC),
  KEY `idx_cfp_adsh` (`adsh`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Pivoted time-series financial data per company per period';
