-- nextcloud.sec_annual_data definition

CREATE TABLE `sec_annual_data` (
  `cik` int(10) unsigned NOT NULL COMMENT 'Company Identifier',
  `year` int(11) NOT NULL COMMENT 'Fiscal Year',
  `ticker` varchar(20) DEFAULT NULL COMMENT 'Trading Symbol at time of fetch',
  `company_name` varchar(255) DEFAULT NULL COMMENT 'Company Name',
  `form` varchar(10) DEFAULT NULL COMMENT 'Source Form (e.g., 10-K)',
  `filed_date` date DEFAULT NULL COMMENT 'Filing Date of the source form',
  `period_end_date` date DEFAULT NULL COMMENT 'Period End Date for the fiscal year',
  `assets` decimal(28,4) DEFAULT NULL COMMENT 'Assets (us-gaap:Assets)',
  `liabilities` decimal(28,4) DEFAULT NULL COMMENT 'Liabilities (us-gaap:Liabilities)',
  `stockholders_equity` decimal(28,4) DEFAULT NULL COMMENT 'StockholdersEquity (us-gaap:StockholdersEquity)',
  `cash_and_equivalents` decimal(28,4) DEFAULT NULL COMMENT 'CashAndEquivalents (us-gaap:CashAndCashEquivalentsAtCarryingValue)',
  `accounts_receivable_net` decimal(28,4) DEFAULT NULL COMMENT 'AccountsReceivableNet (us-gaap:AccountsReceivableNetCurrent)',
  `inventory_net` decimal(28,4) DEFAULT NULL COMMENT 'InventoryNet (us-gaap:InventoryNet)',
  `property_plant_equipment_net` decimal(28,4) DEFAULT NULL COMMENT 'PropertyPlantEquipmentNet (us-gaap:PropertyPlantAndEquipmentNet)',
  `accumulated_depreciation` decimal(28,4) DEFAULT NULL COMMENT 'AccumulatedDepreciation (us-gaap:AccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment)',
  `accounts_payable` decimal(28,4) DEFAULT NULL COMMENT 'AccountsPayable (us-gaap:AccountsPayableCurrent)',
  `accrued_liabilities_current` decimal(28,4) DEFAULT NULL COMMENT 'AccruedLiabilitiesCurrent (us-gaap:AccruedLiabilitiesCurrent)',
  `debt_current` decimal(28,4) DEFAULT NULL COMMENT 'DebtCurrent (us-gaap:DebtCurrent)',
  `long_term_debt_noncurrent` decimal(28,4) DEFAULT NULL COMMENT 'LongTermDebtNoncurrent (us-gaap:LongTermDebtNoncurrent)',
  `revenues` decimal(28,4) DEFAULT NULL COMMENT 'Revenues (us-gaap:Revenues)',
  `cost_of_revenue` decimal(28,4) DEFAULT NULL COMMENT 'CostOfRevenue (us-gaap:CostOfRevenue)',
  `gross_profit` decimal(28,4) DEFAULT NULL COMMENT 'GrossProfit (us-gaap:GrossProfit)',
  `operating_expenses` decimal(28,4) DEFAULT NULL COMMENT 'OperatingExpenses (us-gaap:OperatingExpenses)',
  `operating_income_loss` decimal(28,4) DEFAULT NULL COMMENT 'OperatingIncomeLoss (us-gaap:OperatingIncomeLoss)',
  `interest_expense` decimal(28,4) DEFAULT NULL COMMENT 'InterestExpense (us-gaap:InterestExpense)',
  `income_before_tax` decimal(28,4) DEFAULT NULL COMMENT 'IncomeBeforeTax (us-gaap:IncomeLossFromContinuingOperationsBeforeIncomeTaxExtraordinaryItemsNoncontrollingInterest)',
  `income_tax_expense_benefit` decimal(28,4) DEFAULT NULL COMMENT 'IncomeTaxExpenseBenefit (us-gaap:IncomeTaxExpenseBenefit)',
  `net_income_loss` decimal(28,4) DEFAULT NULL COMMENT 'NetIncomeLoss (us-gaap:NetIncomeLoss)',
  `eps_basic` decimal(18,6) DEFAULT NULL COMMENT 'EPSBasic (us-gaap:EarningsPerShareBasic)',
  `eps_diluted` decimal(18,6) DEFAULT NULL COMMENT 'EPSDiluted (us-gaap:EarningsPerShareDiluted)',
  `shares_outstanding` bigint(20) unsigned DEFAULT NULL COMMENT 'SharesOutstanding (dei:EntityCommonStockSharesOutstanding)',
  `shares_basic_weighted_avg` bigint(20) unsigned DEFAULT NULL COMMENT 'SharesBasicWeightedAvg (us-gaap:WeightedAverageNumberOfSharesOutstandingBasic)',
  `shares_diluted_weighted_avg` bigint(20) unsigned DEFAULT NULL COMMENT 'SharesDilutedWeightedAvg (us-gaap:WeightedAverageNumberOfDilutedSharesOutstanding)',
  `operating_cash_flow` decimal(28,4) DEFAULT NULL COMMENT 'OperatingCashFlow (us-gaap:NetCashProvidedByUsedInOperatingActivities)',
  `capital_expenditures` decimal(28,4) DEFAULT NULL COMMENT 'CapitalExpenditures (us-gaap:PaymentsToAcquirePropertyPlantAndEquipment)',
  `depreciation_and_amortization` decimal(28,4) DEFAULT NULL COMMENT 'DepreciationAndAmortization (us-gaap:DepreciationAndAmortization)',
  `dividends_paid` decimal(28,4) DEFAULT NULL COMMENT 'DividendsPaid (us-gaap:PaymentsOfDividends)',
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`cik`,`year`),
  KEY `idx_sec_annual_ticker` (`ticker`),
  KEY `idx_sec_annual_year` (`year`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Stores selected annual financial data derived from SEC API';