-- nextcloud.sec_annual_data definition

CREATE TABLE `sec_annual_data` (
  `cik` int(10) unsigned NOT NULL COMMENT 'Company Identifier',
  `year` int(11) NOT NULL COMMENT 'Fiscal Year',
  `ticker` varchar(20) DEFAULT NULL COMMENT 'Trading Symbol at time of fetch',
  `company_name` varchar(255) DEFAULT NULL COMMENT 'Company Name',
  `form` varchar(10) DEFAULT NULL COMMENT 'Source Form (e.g., 10-K)',
  `filed_date` date DEFAULT NULL COMMENT 'Filing Date of the source form',
  `period_end_date` date DEFAULT NULL COMMENT 'Period End Date for the fiscal year',
  `assets` decimal(28,4) DEFAULT NULL COMMENT 'Assets (us-gaap:Assets / ifrs-full:Assets)',
  `assets_current` decimal(28,4) DEFAULT NULL COMMENT 'AssetsCurrent (us-gaap:AssetsCurrent)',
  `liabilities` decimal(28,4) DEFAULT NULL COMMENT 'Liabilities (us-gaap:Liabilities)',
  `liabilities_current` decimal(28,4) DEFAULT NULL COMMENT 'LiabilitiesCurrent (us-gaap:LiabilitiesCurrent)',
  `stockholders_equity` decimal(28,4) DEFAULT NULL COMMENT 'StockholdersEquity (us-gaap:StockholdersEquity)',
  `retained_earnings_accumulated_deficit` decimal(28,4) DEFAULT NULL COMMENT 'RetainedEarningsAccumulatedDeficit (us-gaap:RetainedEarningsAccumulatedDeficit)',
  `accumulated_other_comprehensive_income_loss_net_of_tax` decimal(28,4) DEFAULT NULL COMMENT 'AccumulatedOtherComprehensiveIncomeLossNetOfTax (us-gaap:AccumulatedOtherComprehensiveIncomeLossNetOfTax)',
  `common_stock_value` decimal(28,4) DEFAULT NULL COMMENT 'CommonStockValue (us-gaap:CommonStockValue)',
  `additional_paid_in_capital` decimal(28,4) DEFAULT NULL COMMENT 'AdditionalPaidInCapital (us-gaap:AdditionalPaidInCapital)',
  `treasury_stock_value` decimal(28,4) DEFAULT NULL COMMENT 'TreasuryStockValue (us-gaap:TreasuryStockValue)',
  `preferred_stock_value` decimal(28,4) DEFAULT NULL COMMENT 'PreferredStockValue (us-gaap:PreferredStockValue)',
  `noncontrolling_interest` decimal(28,4) DEFAULT NULL COMMENT 'NoncontrollingInterest (us-gaap:NoncontrollingInterest)',
  `cash_and_equivalents` decimal(28,4) DEFAULT NULL COMMENT 'CashAndEquivalents (us-gaap:CashAndCashEquivalentsAtCarryingValue)',
  `marketable_securities_current` decimal(28,4) DEFAULT NULL COMMENT 'MarketableSecuritiesCurrent (us-gaap:MarketableSecuritiesCurrent)',
  `marketable_securities_noncurrent` decimal(28,4) DEFAULT NULL COMMENT 'MarketableSecuritiesNoncurrent (us-gaap:MarketableSecuritiesNoncurrent)',
  `investments` decimal(28,4) DEFAULT NULL COMMENT 'Investments (us-gaap:Investments)',
  `accounts_receivable_net` decimal(28,4) DEFAULT NULL COMMENT 'AccountsReceivableNet (us-gaap:AccountsReceivableNetCurrent)',
  `prepaid_expense_current` decimal(28,4) DEFAULT NULL COMMENT 'PrepaidExpenseCurrent (us-gaap:PrepaidExpenseCurrent)',
  `inventory_net` decimal(28,4) DEFAULT NULL COMMENT 'InventoryNet (us-gaap:InventoryNet)',
  `other_assets_current` decimal(28,4) DEFAULT NULL COMMENT 'OtherAssetsCurrent (us-gaap:OtherAssetsCurrent)',
  `deferred_tax_assets_net_current` decimal(28,4) DEFAULT NULL COMMENT 'DeferredTaxAssetsNetCurrent (us-gaap:DeferredTaxAssetsNetCurrent)',
  `property_plant_equipment_net` decimal(28,4) DEFAULT NULL COMMENT 'PropertyPlantEquipmentNet (us-gaap:PropertyPlantAndEquipmentNet)',
  `goodwill` decimal(28,4) DEFAULT NULL COMMENT 'Goodwill (us-gaap:Goodwill)',
  `intangible_assets_net_excluding_goodwill` decimal(28,4) DEFAULT NULL COMMENT 'IntangibleAssetsNetExcludingGoodwill (us-gaap:IntangibleAssetsNetExcludingGoodwill)',
  `other_assets_noncurrent` decimal(28,4) DEFAULT NULL COMMENT 'OtherAssetsNoncurrent (us-gaap:OtherAssetsNoncurrent)',
  `deferred_tax_assets_net_noncurrent` decimal(28,4) DEFAULT NULL COMMENT 'DeferredTaxAssetsNetNoncurrent (us-gaap:DeferredTaxAssetsNetNoncurrent)',
  `accumulated_depreciation` decimal(28,4) DEFAULT NULL COMMENT 'AccumulatedDepreciation (us-gaap:AccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment)',
  `accounts_payable` decimal(28,4) DEFAULT NULL COMMENT 'AccountsPayable (us-gaap:AccountsPayableCurrent)',
  `income_taxes_payable` decimal(28,4) DEFAULT NULL COMMENT 'IncomeTaxesPayable (us-gaap:IncomeTaxesPayable)',
  `accrued_liabilities_current` decimal(28,4) DEFAULT NULL COMMENT 'AccruedLiabilitiesCurrent (us-gaap:AccruedLiabilitiesCurrent)',
  `deferred_revenue_current` decimal(28,4) DEFAULT NULL COMMENT 'DeferredRevenueCurrent (us-gaap:DeferredRevenueCurrent)',
  `debt_current` decimal(28,4) DEFAULT NULL COMMENT 'DebtCurrent (us-gaap:DebtCurrent)',
  `other_liabilities_current` decimal(28,4) DEFAULT NULL COMMENT 'OtherLiabilitiesCurrent (us-gaap:OtherLiabilitiesCurrent)',
  `long_term_debt_noncurrent` decimal(28,4) DEFAULT NULL COMMENT 'LongTermDebtNoncurrent (us-gaap:LongTermDebtNoncurrent)',
  `deferred_revenue_noncurrent` decimal(28,4) DEFAULT NULL COMMENT 'DeferredRevenueNoncurrent (us-gaap:DeferredRevenueNoncurrent)',
  `other_liabilities_noncurrent` decimal(28,4) DEFAULT NULL COMMENT 'OtherLiabilitiesNoncurrent (us-gaap:OtherLiabilitiesNoncurrent)',
  `deferred_tax_liabilities_noncurrent` decimal(28,4) DEFAULT NULL COMMENT 'DeferredTaxLiabilitiesNoncurrent (us-gaap:DeferredTaxLiabilitiesNoncurrent)',
  `commitments_and_contingencies` decimal(28,4) DEFAULT NULL COMMENT 'CommitmentsAndContingencies (us-gaap:CommitmentsAndContingencies)',
  `revenues` decimal(28,4) DEFAULT NULL COMMENT 'Revenues (us-gaap:Revenues)',
  `cost_of_revenue` decimal(28,4) DEFAULT NULL COMMENT 'CostOfRevenue (us-gaap:CostOfRevenue)',
  `depreciation_expense` decimal(28,4) DEFAULT NULL COMMENT 'DepreciationExpense (us-gaap:Depreciation)',
  `amortization_of_intangible_assets` decimal(28,4) DEFAULT NULL COMMENT 'AmortizationOfIntangibleAssets (us-gaap:AmortizationOfIntangibleAssets)',
  `gross_profit` decimal(28,4) DEFAULT NULL COMMENT 'GrossProfit (us-gaap:GrossProfit)',
  `operating_expenses` decimal(28,4) DEFAULT NULL COMMENT 'OperatingExpenses (us-gaap:OperatingExpenses)',
  `selling_general_and_administrative_expense` decimal(28,4) DEFAULT NULL COMMENT 'SellingGeneralAndAdministrativeExpense (us-gaap:SellingGeneralAndAdministrativeExpense)',
  `research_and_development_expense` decimal(28,4) DEFAULT NULL COMMENT 'ResearchAndDevelopmentExpense (us-gaap:ResearchAndDevelopmentExpense)',
  `operating_income_loss` decimal(28,4) DEFAULT NULL COMMENT 'OperatingIncomeLoss (us-gaap:OperatingIncomeLoss)',
  `other_operating_income_expense_net` decimal(28,4) DEFAULT NULL COMMENT 'OtherOperatingIncomeExpenseNet (us-gaap:OtherOperatingIncomeExpenseNet)',
  `interest_expense` decimal(28,4) DEFAULT NULL COMMENT 'InterestExpense (us-gaap:InterestExpense)',
  `interest_income_expense_net` decimal(28,4) DEFAULT NULL COMMENT 'InterestIncomeExpenseNet (us-gaap:InterestIncomeExpenseNet)',
  `interest_income` decimal(28,4) DEFAULT NULL COMMENT 'InterestIncome (us-gaap:InterestIncome)',
  `other_nonoperating_income_expense` decimal(28,4) DEFAULT NULL COMMENT 'OtherNonoperatingIncomeExpense (us-gaap:OtherNonoperatingIncomeExpense)',
  `income_before_tax` decimal(28,4) DEFAULT NULL COMMENT 'IncomeBeforeTax (us-gaap:IncomeLossFromContinuingOperationsBeforeIncomeTaxExtraordinaryItemsNoncontrollingInterest)',
  `income_tax_expense_benefit` decimal(28,4) DEFAULT NULL COMMENT 'IncomeTaxExpenseBenefit (us-gaap:IncomeTaxExpenseBenefit)',
  `income_tax_expense_benefit_continuing_operations` decimal(28,4) DEFAULT NULL COMMENT 'IncomeTaxExpenseBenefitContinuingOperations (us-gaap:IncomeTaxExpenseBenefitContinuingOperations)',
  `income_loss_from_continuing_operations_after_tax` decimal(28,4) DEFAULT NULL COMMENT 'IncomeLossFromContinuingOperationsAfterTax (us-gaap:IncomeLossFromContinuingOperationsAfterTax)',
  `income_loss_from_discontinued_operations_net_of_tax` decimal(28,4) DEFAULT NULL COMMENT 'IncomeLossFromDiscontinuedOperationsNetOfTax (us-gaap:IncomeLossFromDiscontinuedOperationsNetOfTax)',
  `net_income_loss` decimal(28,4) DEFAULT NULL COMMENT 'NetIncomeLoss (us-gaap:NetIncomeLoss / ifrs-full:ProfitLoss)',
  `comprehensive_income_net_of_tax` decimal(28,4) DEFAULT NULL COMMENT 'ComprehensiveIncomeNetOfTax (us-gaap:ComprehensiveIncomeNetOfTax)',
  `eps_basic` decimal(18,6) DEFAULT NULL COMMENT 'EPSBasic (us-gaap:EarningsPerShareBasic)',
  `eps_diluted` decimal(18,6) DEFAULT NULL COMMENT 'EPSDiluted (us-gaap:EarningsPerShareDiluted)',
  `shares_outstanding` bigint(20) unsigned DEFAULT NULL COMMENT 'SharesOutstanding (dei:EntityCommonStockSharesOutstanding)',
  `shares_basic_weighted_avg` bigint(20) unsigned DEFAULT NULL COMMENT 'SharesBasicWeightedAvg (us-gaap:WeightedAverageNumberOfSharesOutstandingBasic)',
  `shares_diluted_weighted_avg` bigint(20) unsigned DEFAULT NULL COMMENT 'SharesDilutedWeightedAvg (us-gaap:WeightedAverageNumberOfDilutedSharesOutstanding)',
  `operating_cash_flow` decimal(28,4) DEFAULT NULL COMMENT 'OperatingCashFlow (us-gaap:NetCashProvidedByUsedInOperatingActivities)',
  `capital_expenditures` decimal(28,4) DEFAULT NULL COMMENT 'CapitalExpenditures (us-gaap:PaymentsToAcquirePropertyPlantAndEquipment)',
  `depreciation_and_amortization` decimal(28,4) DEFAULT NULL COMMENT 'DepreciationAndAmortization (us-gaap:DepreciationAndAmortization)',
  `dividends_paid` decimal(28,4) DEFAULT NULL COMMENT 'DividendsPaid (us-gaap:PaymentsOfDividends)',
  `calculated_free_cash_flow` decimal(28,4) DEFAULT NULL COMMENT 'Calculated Free Cash Flow (OperatingCashFlow - CapitalExpenditures)',
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`cik`,`year`),
  KEY `idx_sec_annual_ticker` (`ticker`),
  KEY `idx_sec_annual_year` (`year`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Stores selected annual financial data derived from SEC API';